version: 2.1

jobs:
  say-hello:
    machine:
      image: 'windows-server-2022'
    resource_class: windows.large
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: 'echo Hello, World!'

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
