version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/server-2022:large
    steps:
      - checkout
      - run:
          name: Pull image Windows Server Core
          command: docker pull mcr.microsoft.com/windows/servercore:ltsc2022
      - run:
          name: Lancer un conteneur et exécuter une commande
          command: docker run --rm mcr.microsoft.com/windows/servercore:ltsc2022 cmd /c echo "Hello depuis le conteneur Windows"
      - run:
          name: Hello depuis la VM
          command: Write-Host 'Hello, Windows VM'

workflows:
  my-workflow:
    jobs:
      - build
