version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/server-2022
    resource_class: large
    steps:
      - checkout
      - run:
          name: Docker login
          command: docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_PAT
      - run:
          name: Pull Windows Server Core
          command: docker pull mcr.microsoft.com/windows/servercore:ltsc2022
      - run:
          name: Lancer conteneur
          command: docker run --rm mcr.microsoft.com/windows/servercore:ltsc2022 cmd /c echo "Hello depuis ServerCore ltsc2022"
      - run:
          name: Hello depuis la VM
          command: Write-Host "Hello depuis l'executor Windows"
          
workflows:
  my-workflow:
    jobs:
      - buil
      d
