version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build-unreal-project:
    executor:
      name: win/server-2022
      size: large
    
    environment:
      PROJECT_NAME: "fortalia"
      UE5_DOCKER_IMAGE: "vmilletdev/unreal-engine:5.6.1"
    
    steps:
      - checkout
      
      - run:
          name: Build and Cook Unreal Engine Project
          shell: powershell.exe
          command: |
            # Définir les chemins
            $projectPath = "C:\${env:PROJECT_NAME}"
            $checkoutPath = $PWD.Path
            
            Write-Host "Checkout path: $checkoutPath"
            Write-Host "Project path: $projectPath"
            Write-Host "Docker image: ${env:UE5_DOCKER_IMAGE}"
            
            # Exécuter le build dans le conteneur Docker
            docker run --rm `
              -v "${checkoutPath}:${projectPath}" `
              ${env:UE5_DOCKER_IMAGE} `
              powershell -Command "
                & 'C:\UnrealEngine\Engine\Build\BatchFiles\RunUAT.bat' `
                  BuildCookRun `
                  -project='${projectPath}\${env:PROJECT_NAME}.uproject' `
                  -platform=Win64 `
                  -clientconfig=Development `
                  -serverconfig=Development `
                  -cook `
                  -allmaps `
                  -build `
                  -stage `
                  -archive `
                  -archivedirectory='${projectPath}\Build' `
                  -pak `
                  -prereqs `
                  -nodebuginfo
              "
      
      - run:
          name: Zip Build Output
          shell: powershell.exe
          command: |
            $buildPath = "Build\Windows"
            $zipPath = "Build\${env:PROJECT_NAME}-Windows.zip"
            
            Write-Host "Compressing build output from $buildPath"
            
            if (Test-Path $buildPath) {
              Compress-Archive -Path "$buildPath\*" -DestinationPath $zipPath -Force
              Write-Host "Build archived to $zipPath"
            } else {
              Write-Error "Build path $buildPath not found"
              exit 1
            }
      
      - store_artifacts:
          path: Build/${PROJECT_NAME}-Windows.zip
          destination: unreal-build

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-unreal-project
