version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    resource_class: 'windows.medium'
    steps:
      - checkout
      - run:
          name: Pull image Windows Server Core
          command: docker pull mcr.microsoft.com/windows/servercore:ltsc2022
      - run:
          name: Lancer un conteneur et exécuter une commande
          command: docker run --rm mcr.microsoft.com/windows/servercore:ltsc2022 cmd /c echo "Hello depuis le conteneur Windows"
      - run:
          name: Hello depuis la VM
          command: Write-Host 'Hello, Windows VM'

workflows:
  my-workflow:
    jobs:
      - build
