version: 2.1

jobs:
  build:
    machine:
      image: 'vmilletdev/unreal-engine:5.6.1'
    environment:
      DOCKER_IMAGE: "vmilletdev/unreal-engine:5.6.1"
      PROJECT_NAME: "fortalia"
    steps:
      - checkout
      - run:
          name: Pull image Unreal Engine
          no_output_timeout: 40m
          command: docker pull $Env:DOCKER_IMAGE
      - run:
          name: Package Unreal project
          command: |
            docker run --rm -v "$env:CIRCLE_WORKING_DIRECTORY\$env:PROJECT_NAME:C:\$env:PROJECT_NAME" $Env:DOCKER_IMAGE Engine\Build\BatchFiles\RunUAT.bat BuildCookRun ^
             -project=C:\$env:PROJECT_NAME\$env:PROJECT_NAME.uproject ^
             -noP4 ^
             -platform=Win64 ^
             -clientconfig=Shipping ^
             -build ^
             -cook ^
             -stage ^
             -package ^
             -archive ^
             -archivedirectory=C:\$env:PROJECT_NAME\Build

workflows:
  my-workflow:
    jobs:
      - build
