version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    resource_class: 'windows.large'
    environment:
      DOCKER_IMAGE: "vmilletdev/unreal-engine:5.6"
    steps:
      - checkout
      - run:
          name: Pull image Unreal Engine
          no_output_timeout: 40m
          command: docker pull $Env:DOCKER_IMAGE
      - run:
          name: Lancer un conteneur et exécuter une commande
          command: docker run --rm $Env:DOCKER_IMAGE cmd /c echo "Hello depuis le conteneur Windows"
      - run:
          name: Hello depuis la VM
          command: Write-Host 'Hello, Windows VM'

workflows:
  my-workflow:
    jobs:
      - build
